### ISSUE TITLE
/proxy/change route stuck in pending

### ISSUE THREAD

**Issue by Armanio** [Soundmark/proxy-switch-plugin#1]
Hey @Soundmark!
Thx for great plugin - you safe many my work hours!

I noticed strange thing: when i changed proxy url network request to `/proxy/change` stuck in pending status.

<img width="749" alt="Снимок экрана 2022-05-11 в 13 23 18" src="https://user-images.githubusercontent.com/3195714/167828245-74155571-7473-4421-926e-10924875a732.png">

If change res.status(200) to res.status(200).json({}) then problem is solved
If you want i could create PR with fixes 

Sorry for my bad english - its not my native language, feel free to correct me :)

**Comment by Soundmark** [comment]
@Armanio Thanks for your careful usage of the plugin, I've never noticed this problem. 

You could create PR for this fixes.☺️
